version: 1.2.{build}
image: Visual Studio 2017
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  assembly_version: '{version}'
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
